### ISSUE TITLE
"This browser or app may not be secure." during log in.

### ISSUE THREAD

**Issue by vadim-cherepanov** [ankurk91/google-chat-electron#113] opened 2022-09-14 13:29 UTC
Having this issue. There is another issue on this topic, but it is locked by someone for some reason. The trick with **Help > Toggle External Links Guard** worked for me. Is there any progress with this issue, as this app is the only one with Google authentication that I have and that has this problem?

**Comment by ankurk91** [comment] 2022-09-14 15:42
Duplicate of
https://github.com/ankurk91/google-chat-electron/issues/52

The orignal issue is still open, it means there is no solution yet

**Closed as completed by ankurk91** 2022-09-14 15:42 UTC
