### ISSUE TITLE
Unable to hear notification sounds in MAC OS X

### ISSUE THREAD

**Issue by satyakommula96** [ankurk91/google-chat-electron#58] opened 2022-01-25 07:36 UTC
Notifications are working. But I'm unable to hear notification sounds in Mac OS Montery

**Comment by ankurk91** [comment] 2022-01-25 08:19
Hi, electron itself does not support sound in notification.
Duplicate of https://github.com/ankurk91/google-chat-electron/issues/50

**Closed by ankurk91** 2022-01-25 08:19 UTC
