### ISSUE TITLE
[mac] Allow to Hide tray icon

### ISSUE THREAD

**Issue by fblupi** [ankurk91/google-chat-electron#93] opened 2022-05-30 07:18 UTC
Almost every app let me decide if I whether want to show the tray icon or not. It could be nice if this app makes it possible too.

**Comment by ankurk91** [comment] 2022-05-30 07:20
Duplicate of 
https://github.com/ankurk91/google-chat-electron/issues/51

**Comment by ankurk91** [comment] 2022-06-24 17:15
I don't think this would benifit many users.

The chat apps are suppose to run all the time, tray icon let the app work and run in background.

**Closed by ankurk91** 2022-06-24 17:15 UTC
