### ISSUE TITLE
No notification sound

### ISSUE THREAD

**Issue by B0ndo2** [ankurk91/google-chat-electron#65] opened 2022-02-14 16:44 UTC
I have notification sound enabled and I can hear it when I test it from settings but when I receive a message, I only get popups.
Fedora 35 with KDE
Installed via Snap

**Comment by ankurk91** [comment] 2022-02-14 16:46
I would suggest to work without sound it boost productivity. :p

Duplicate of

https://github.com/ankurk91/google-chat-electron/issues/64

**Closed by ankurk91** 2022-02-14 16:46 UTC

**Comment by B0ndo2** [comment] 2022-02-22 22:54
I am actually getting sound notification sometimes on my Fedora 35 so it looks like it works intermittently ?
